### ISSUE TITLE
No Module Named edgegrid

### ISSUE THREAD

**Issue by maheshvemuri** [akamai/api-kickstart#66]
I am trying to use examples/python and replaced my credentials in place holders. But, not able to build the script. I am always getting this error
```
from akamai.edgegrid import EdgeGridAuth
ImportError: No module named edgegrid
```
Also, gen_edgerc.py is not working

```
E:\akamai\api-kickstart\examples\python>python ./gen_edgerc.py -s papi
Akamai OPEN API EdgeGrid Credentials

This script will create a 'papi' section in the local ~/.edgerc credential file.

After authorizing your client in the {OPEN} API Administration tool,
export the credentials and paste the contents of the export file below,
followed by control-D.

>>>
client_secret = a7dPtxxxxxxxxxxxxxxx7iqZXdIZJAxxxxxYAVG26k=
host = akab-mj6heazegeax6e2n-vXXXXXXXXXXXXXX.luna.akamaiapis.net
access_token = akab-wxxxxxxxxxxx7hlb-5rslfxxxxxxxxcc6
client_token = akab-dgbfxxxxxxxxxxxw-jnvd7xxxxxx3mswe^Z
^Z
+++ Found credentials file: C:\Users\Mahesh/.edgerc
>>> Replacing section: papi
*** OK TO REPLACE section papi? *** [Y|n]:Y


Done. Please verify your credentials with the verify_creds.py script using verify_creds.py -s papi.


E:\akamai\api-kickstart\examples\python>python verify_creds.py
Traceback (most recent call last):
  File "verify_creds.py", line 25, in <module>
    from http_calls import EdgeGridHttpCaller
  File "E:\akamai\api-kickstart\examples\python\http_calls.py", line 28, in <module>
    from akamai.edgegrid import EdgeGridAuth
ImportError: No module named edgegrid
```

**Comment by synedra** [comment]
You need to follow the instructions and cd into tools and run sudo setup.py install.

Kirsten

**Comment by maheshvemuri** [comment]
I have done. I am getting below log

```
running install
running bdist_egg
running egg_info
creating akamaikickstart.egg-info
writing requirements to akamaikickstart.egg-info\requires.txt
writing akamaikickstart.egg-info\PKG-INFO
writing top-level names to akamaikickstart.egg-info\top_level.txt
writing dependency_links to akamaikickstart.egg-info\dependency_links.txt
writing manifest file 'akamaikickstart.egg-info\SOURCES.txt'
reading manifest file 'akamaikickstart.egg-info\SOURCES.txt'
writing manifest file 'akamaikickstart.egg-info\SOURCES.txt'
installing library code to build\bdist.win32\egg
**running install_lib
warning: install_lib: 'build\lib' does not exist -- no Python modules to install**

creating build
creating build\bdist.win32
creating build\bdist.win32\egg
creating build\bdist.win32\egg\EGG-INFO
copying akamaikickstart.egg-info\PKG-INFO -> build\bdist.win32\egg\EGG-INFO
copying akamaikickstart.egg-info\SOURCES.txt -> build\bdist.win32\egg\EGG-INFO
copying akamaikickstart.egg-info\dependency_links.txt -> build\bdist.win32\egg\EGG-INFO
copying akamaikickstart.egg-info\requires.txt -> build\bdist.win32\egg\EGG-INFO
copying akamaikickstart.egg-info\top_level.txt -> build\bdist.win32\egg\EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist\akamaikickstart-1.0.0-py2.7.egg' and adding 'build\bdist.win32\egg' to it
removing 'build\bdist.win32\egg' (and everything under it)
Processing akamaikickstart-1.0.0-py2.7.egg
Removing c:\python27\lib\site-packages\akamaikickstart-1.0.0-py2.7.egg
Copying akamaikickstart-1.0.0-py2.7.egg to c:\python27\lib\site-packages
akamaikickstart 1.0.0 is already the active version in easy-install.pth

Installed c:\python27\lib\site-packages\akamaikickstart-1.0.0-py2.7.egg
Processing dependencies for akamaikickstart==1.0.0
Searching for gitpython==2.1.8
Best match: gitpython 2.1.8
Processing gitpython-2.1.8-py2.7.egg
gitpython 2.1.8 is already the active version in easy-install.pth

Using c:\python27\lib\site-packages\gitpython-2.1.8-py2.7.egg
Searching for edgegrid-python==1.1.1
Best match: edgegrid-python 1.1.1
Processing edgegrid_python-1.1.1-py2.7.egg
edgegrid-python 1.1.1 is already the active version in easy-install.pth

Using c:\python27\lib\site-packages\edgegrid_python-1.1.1-py2.7.egg
Searching for gitdb2==2.0.3
Best match: gitdb2 2.0.3
Processing gitdb2-2.0.3-py2.7.egg
gitdb2 2.0.3 is already the active version in easy-install.pth

Using c:\python27\lib\site-packages\gitdb2-2.0.3-py2.7.egg
Searching for urllib3==1.22
Best match: urllib3 1.22
Processing urllib3-1.22-py2.7.egg
urllib3 1.22 is already the active version in easy-install.pth

Using c:\python27\lib\site-packages\urllib3-1.22-py2.7.egg
Searching for pyasn1==0.4.2
Best match: pyasn1 0.4.2
Processing pyasn1-0.4.2-py2.7.egg
pyasn1 0.4.2 is already the active version in easy-install.pth

Using c:\python27\lib\site-packages\pyasn1-0.4.2-py2.7.egg
Searching for ndg-httpsclient==0.4.4
Best match: ndg-httpsclient 0.4.4
Processing ndg_httpsclient-0.4.4-py2.7.egg
ndg-httpsclient 0.4.4 is already the active version in easy-install.pth
Installing ndg_httpclient-script.py script to C:\Python27\Scripts
Installing ndg_httpclient.exe script to C:\Python27\Scripts
Installing ndg_httpclient.exe.manifest script to C:\Python27\Scripts

Using c:\python27\lib\site-packages\ndg_httpsclient-0.4.4-py2.7.egg
Searching for pyopenssl==17.5.0
Best match: pyopenssl 17.5.0
Processing pyopenssl-17.5.0-py2.7.egg
pyopenssl 17.5.0 is already the active version in easy-install.pth

Using c:\python27\lib\site-packages\pyopenssl-17.5.0-py2.7.egg
Searching for requests==2.12.4
Best match: requests 2.12.4
Adding requests 2.12.4 to easy-install.pth file

Using c:\python27\lib\site-packages
Searching for smmap2==2.0.3
Best match: smmap2 2.0.3
Processing smmap2-2.0.3-py2.7.egg
smmap2 2.0.3 is already the active version in easy-install.pth

Using c:\python27\lib\site-packages\smmap2-2.0.3-py2.7.egg
Searching for six==1.10.0
Best match: six 1.10.0
Adding six 1.10.0 to easy-install.pth file

Using c:\python27\lib\site-packages
Searching for cryptography==2.1.4
Best match: cryptography 2.1.4
Adding cryptography 2.1.4 to easy-install.pth file

Using c:\python27\lib\site-packages
Searching for ipaddress==1.0.19
Best match: ipaddress 1.0.19
Adding ipaddress 1.0.19 to easy-install.pth file

Using c:\python27\lib\site-packages
Searching for idna==2.6
Best match: idna 2.6
Adding idna 2.6 to easy-install.pth file

Using c:\python27\lib\site-packages
Searching for asn1crypto==0.24.0
Best match: asn1crypto 0.24.0
Adding asn1crypto 0.24.0 to easy-install.pth file

Using c:\python27\lib\site-packages
Searching for enum34==1.1.6
Best match: enum34 1.1.6
Adding enum34 1.1.6 to easy-install.pth file

Using c:\python27\lib\site-packages
Searching for cffi==1.11.4
Best match: cffi 1.11.4
Adding cffi 1.11.4 to easy-install.pth file

Using c:\python27\lib\site-packages
Searching for pycparser==2.18
Best match: pycparser 2.18
Adding pycparser 2.18 to easy-install.pth file

Using c:\python27\lib\site-packages
Finished processing dependencies for akamaikickstart==1.0.0
```

**Comment by synedra** [comment]
Perhaps you have more than one version of python installed on your system.

The install shows you have edgegrid:
edgegrid-python 1.1.1 is already the active version in easy-install.pth

You may want to use the docker container so you don’t have to manage the python installations.

I think your easy install path is not the same as your python path, but that’s a system setup issue.

Kirsten

**Comment by maheshvemuri** [comment]
I have only one version of Python installed (2.7). Also, easy install and python have same path.
Could there be anything else causing this issue?

**Comment by kitsushadow** [comment]
I also have the same issue.

`Traceback (most recent call last):
  File "/Users/mminaie/development/Blackstone/WCM/wcm_reporting/og_hits_api.py", line 5, in <module>
    from akamai.edgegrid import EdgeGridAuth
ModuleNotFoundError: No module named 'akamai'
`
` mminaie ~ $ pip install edgegrid-python
Requirement already satisfied: edgegrid-python in /usr/local/lib/python2.7/site-packages (1.1.1)
Requirement already satisfied: urllib3 in ./Library/Python/2.7/lib/python/site-packages (from edgegrid-python) (1.22)
Requirement already satisfied: ndg-httpsclient in /usr/local/lib/python2.7/site-packages (from edgegrid-python) (0.5.1)
Requirement already satisfied: requests>=2.3.0 in ./Library/Python/2.7/lib/python/site-packages (from edgegrid-python) (2.18.4)
Requirement already satisfied: pyasn1 in ./Library/Python/2.7/lib/python/site-packages (from edgegrid-python) (0.4.2)
Requirement already satisfied: pyOpenSSL>=0.13 in /usr/local/lib/python2.7/site-packages (from edgegrid-python) (19.0.0)
Requirement already satisfied: certifi>=2017.4.17 in ./Library/Python/2.7/lib/python/site-packages (from requests>=2.3.0->edgegrid-python) (2018.1.18)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./Library/Python/2.7/lib/python/site-packages (from requests>=2.3.0->edgegrid-python) (3.0.4)
Requirement already satisfied: idna<2.7,>=2.5 in ./Library/Python/2.7/lib/python/site-packages (from requests>=2.3.0->edgegrid-python) (2.6)
Requirement already satisfied: six>=1.5.2 in ./Library/Python/2.7/lib/python/site-packages (from pyOpenSSL>=0.13->edgegrid-python) (1.11.0)
Requirement already satisfied: cryptography>=2.3 in /usr/local/lib/python2.7/site-packages (from pyOpenSSL>=0.13->edgegrid-python) (2.6.1)
Requirement already satisfied: enum34; python_version < "3" in /usr/local/lib/python2.7/site-packages (from cryptography>=2.3->pyOpenSSL>=0.13->edgegrid-python) (1.1.6)
Requirement already satisfied: cffi!=1.11.3,>=1.8 in /usr/local/lib/python2.7/site-packages (from cryptography>=2.3->pyOpenSSL>=0.13->edgegrid-python) (1.12.2)
Requirement already satisfied: asn1crypto>=0.21.0 in /usr/local/lib/python2.7/site-packages (from cryptography>=2.3->pyOpenSSL>=0.13->edgegrid-python) (0.24.0)
Requirement already satisfied: ipaddress; python_version < "3" in /usr/local/lib/python2.7/site-packages (from cryptography>=2.3->pyOpenSSL>=0.13->edgegrid-python) (1.0.22)
Requirement already satisfied: pycparser in /usr/local/lib/python2.7/site-packages (from cffi!=1.11.3,>=1.8->cryptography>=2.3->pyOpenSSL>=0.13->edgegrid-python) (2.19)`

**Comment by synedra** [comment]
I'm not sure what you've got in your development environment, as you're trying to use the library with your own code.  This is a very specific code repository for people to try out things, I don't know how to make it work with your own internal code.
